### ISSUE TITLE
Compare to SimVQ

### ISSUE THREAD

**Issue by suruoxi** [TencentARC/SEED-Voken#43]
Have you compared  IBQ to SimVQ?  I think SimVQ has the similar motivation of "optimize all codebook embeddings".

**Comment by ShiFengyuan1999** [comment]
Hi @suruoxi, thanks for your interest in our work. 

SimVQ has a similar motivation to IBQ, but we adopt different methods to optimize all codebook embeddings. SimVQ optimizes a linear transformation space $W \in R^{D \times D}$, while our IBQ optimizes the codes ($C \in R^K\times D$) themselves, where $K\gg D$.

It can not compare SimVQ with IBQ directly, because SimVQ is trained on ImageNet 128x128 and IBQ is trained on ImageNet 256x256. Moreover, SimVQ only shows the reconstruction performance and does not give the generation results. But we can provide some results from the papers for reference.

| Method | Train Resolution  | Codebook Size | rFID $\downarrow$ |
| :----  | :----  | :----  | :----  |
| SimVQ  | 128 $\times$ 128 | 262144 | 1.99 |
| OpenMAGVIT2  | 128 $\times$ 128  | 262144 | 1.18 |
| OpenMAGVIT2  | 256 $\times$ 256  | 262144 | 1.17 |
| IBQ  | 256 $\times$ 256  | 262144 | 1.00 |

**Comment by suruoxi** [comment]
thanks  for  the  reply,  the  rFID of IBQ is impressive.
